
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.nxroads.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.nxroads.NxRoadsAndSkycrapersMod;

public class NxRoadsAndSkycrapersModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, NxRoadsAndSkycrapersMod.MODID);
	public static final RegistryObject<CreativeModeTab> CREATIVE_TAB_NX_ROADS = REGISTRY.register("creative_tab_nx_roads", () -> CreativeModeTab.builder().title(Component.translatable("item_group.nx_roads_and_skycrapers.creative_tab_nx_roads"))
			.icon(() -> new ItemStack(NxRoadsAndSkycrapersModBlocks.STRAIGHT_LEFT_RIGHT_ARROW_YELLOW_ROAD.get())).displayItems((parameters, tabData) -> {
				tabData.accept(NxRoadsAndSkycrapersModBlocks.PLAIN_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.ARROW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.ARROW_RIGHT_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.ARROW_STRAIGHT_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.ARROW_LEFT_RIGHT_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.ARROW_STRAIGHT_LEFT_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.ARROW_STRAIGHT_RIGHT_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.ARROW_STRAIGHT_RIGHT_LEFT_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.CROSWALK_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_IN_EX_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_OUT_EX_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.OUTER_LINE_EX_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.TURN_IN_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.OUTER_LINE_SIMPLE_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.TURN_OUT_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.EX_ZONE_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.TURN_IN_EX_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.TURN_OUT_EX_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_LINE_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MERGE_LINE_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.LINE_STOP_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_LINE_DOUBLE_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_TURN_LINE_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_LINE_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_CROSS_LINE_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_T_LINE_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_TURN_LINE_SINGLE_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SPLIT_IN_LEFT_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SPLIT_IN_RIGHT_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SPLIT_OUT_LEFT_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SPLIT_OUT_RIGHT_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.PLAIN_SLOPE_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_IN_E_SLOPE_ROAD_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_IN_N_SLOPE_ROAD_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SINGLE_MIDDLE_LINE_SLOPE_ROAD_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_IN_SX_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_IN_WX_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_OUT_EX_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_OUT_NX_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_OUT_SX_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_OUT_WX_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.EXCL_LEFT_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.EXCL_RIGHT_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_DOUBLE_LINE_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SINGLE_LEFT_LINE_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SINGLE_RIGHT_LINE_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_SINGLE_LINE_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.PLAIN_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.LEFT_ARROW_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.RIGHT_ARROW_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.LEFT_RIGHT_ARROW_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STRAIGHT_ARROW_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STRAIGHT_LEFT_ARROW_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STRAIGHT_RIGHT_ARROW_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STRAIGHT_LEFT_RIGHT_ARROW_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.CROSSWALK_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_IN_EXCL_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_OUT_EXCL_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.OUTER_LINE_EXCL_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.TURN_IN_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.OUTER_SINGLE_LINE_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.TURN_OUT_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.EXCL_ZONE_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.TURN_IN_EXCL_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.TURN_OUT_EXCL_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.DIAGONAL_SIMPLE_LINE_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MERGE_LINE_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STOP_LINE_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_DOBBLE_LINE_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_TURN_DOUBLE_LINE_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_SINGLE_LINE_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDEL_CROSS_LINE_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_T_LINE_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_TURN_LINE_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SPLIT_IN_RIGHT_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SPLIT_IN_LEFT_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SPLIT_OUT_RIGHT_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SPLIT_OUT_LEFT_YELLOW_ROAD.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SINGLE_MIDDLE_LINE_YELLOW_SLOPE_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.EXCL_LEFT_YELLOW_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.EXCL_RIGHT_YELLOW_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MIDDLE_DOUBLE_YELLOW_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SINGLE_LEFT_YELLOW_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SINGLE_RIGHT_YELLOW_X_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModItems.YELLOW_ROAD_DYE.get());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.OUTER_LINE_EX_ROAD_ROTATED.get().asItem());
			}).withSearchBar().build());
	public static final RegistryObject<CreativeModeTab> CREATIVE_TAB_NX_BUILDING_BLOCKS = REGISTRY.register("creative_tab_nx_building_blocks", () -> CreativeModeTab.builder()
			.title(Component.translatable("item_group.nx_roads_and_skycrapers.creative_tab_nx_building_blocks")).icon(() -> new ItemStack(NxRoadsAndSkycrapersModBlocks.CONCRETE_2.get())).displayItems((parameters, tabData) -> {
				tabData.accept(NxRoadsAndSkycrapersModBlocks.CONCRETE_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.CONCRETE_2.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GRANITE_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GRANITE_2.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GRANITE_3.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MARBLE_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MARBLE_2.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MARBLE_3.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MARBLE_4.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MARBLE_5.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MARBLE_6.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MARBLE_7.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.MARBLE_8.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.PAVEMENT_CRACKED_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.PAVEMENT_CRACKED_2.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.PAVEMENT_CRACKED_3.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SIDEWALK_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SIDEWALK_2.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SIDEWALK_3.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SIDEWALK_4.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SIDEWALK_5.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SIDEWALK_6.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SIDEWALK_7.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SIDEWALK_8.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STONE_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STONE_2.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STONE_3.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STONE_4.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STONE_5.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STONE_6.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STONE_7.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STONE_BRICK_CRACKED_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STONE_BRICK_CRACKED_2.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STONE_BRICK_CRACKED_3.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STONE_BRICK_CRACKED_4.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STONE_BRICK_CRACKED_5.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.STONE_BRICK_CRACKED_6.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SKYSCRAPER_BLOCK_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SKYCRAPER_BLOCK_2.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SKYCRAPER_BLOCK_3.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SKYCRAPER_BLOCK_4.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SKYCRAPER_BLOCK_5.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.SKYCRAPER_BLOCK_6.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.WOOD_CEILING_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.WOOD_CEILING_2.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.WOOD_CEILING_3.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.WOOD_CEILING_4.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.WOOD_FLOOR_LONG_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.WOOD_FLOOR_LONG_2.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.WOOD_FLOOR_LONG_3.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.WOOD_FLOOR_LONG_4.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.WOOD_FLOOR_LONG_5.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.WOOD_FLOOR_LONG_6.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.CLASS_0.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_2.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_3.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_4.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_5.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_6.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_7.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_8.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_9.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_10.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_0.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_2.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_3.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_4.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_5.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_6.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_7.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_8.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_9.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_10.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_0.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_1.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_2.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_3.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_4.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_5.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_6.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_7.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_8.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_9.get().asItem());
				tabData.accept(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_10.get().asItem());
			}).withSearchBar().build());
}
