
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.nxroads.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.nxroads.item.YellowRoadDyeItem;
import net.mcreator.nxroads.NxRoadsAndSkycrapersMod;

public class NxRoadsAndSkycrapersModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, NxRoadsAndSkycrapersMod.MODID);
	public static final RegistryObject<Item> PLAIN_ROAD = block(NxRoadsAndSkycrapersModBlocks.PLAIN_ROAD);
	public static final RegistryObject<Item> ARROW_ROAD = block(NxRoadsAndSkycrapersModBlocks.ARROW_ROAD);
	public static final RegistryObject<Item> ARROW_LEFT_RIGHT_ROAD = block(NxRoadsAndSkycrapersModBlocks.ARROW_LEFT_RIGHT_ROAD);
	public static final RegistryObject<Item> ARROW_STRAIGHT_ROAD = block(NxRoadsAndSkycrapersModBlocks.ARROW_STRAIGHT_ROAD);
	public static final RegistryObject<Item> ARROW_STRAIGHT_LEFT_ROAD = block(NxRoadsAndSkycrapersModBlocks.ARROW_STRAIGHT_LEFT_ROAD);
	public static final RegistryObject<Item> ARROW_STRAIGHT_RIGHT_LEFT_ROAD = block(NxRoadsAndSkycrapersModBlocks.ARROW_STRAIGHT_RIGHT_LEFT_ROAD);
	public static final RegistryObject<Item> ARROW_STRAIGHT_RIGHT_ROAD = block(NxRoadsAndSkycrapersModBlocks.ARROW_STRAIGHT_RIGHT_ROAD);
	public static final RegistryObject<Item> CROSWALK_ROAD = block(NxRoadsAndSkycrapersModBlocks.CROSWALK_ROAD);
	public static final RegistryObject<Item> DIAGONAL_IN_EX_ROAD = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_IN_EX_ROAD);
	public static final RegistryObject<Item> DIAGONAL_OUT_EX_ROAD = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_OUT_EX_ROAD);
	public static final RegistryObject<Item> OUTER_LINE_EX_ROAD = block(NxRoadsAndSkycrapersModBlocks.OUTER_LINE_EX_ROAD);
	public static final RegistryObject<Item> TURN_IN_ROAD = block(NxRoadsAndSkycrapersModBlocks.TURN_IN_ROAD);
	public static final RegistryObject<Item> OUTER_LINE_SIMPLE_ROAD = block(NxRoadsAndSkycrapersModBlocks.OUTER_LINE_SIMPLE_ROAD);
	public static final RegistryObject<Item> TURN_OUT_ROAD = block(NxRoadsAndSkycrapersModBlocks.TURN_OUT_ROAD);
	public static final RegistryObject<Item> EX_ZONE_ROAD = block(NxRoadsAndSkycrapersModBlocks.EX_ZONE_ROAD);
	public static final RegistryObject<Item> TURN_IN_EX_ROAD = block(NxRoadsAndSkycrapersModBlocks.TURN_IN_EX_ROAD);
	public static final RegistryObject<Item> TURN_OUT_EX_ROAD = block(NxRoadsAndSkycrapersModBlocks.TURN_OUT_EX_ROAD);
	public static final RegistryObject<Item> DIAGONAL_LINE_ROAD = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_LINE_ROAD);
	public static final RegistryObject<Item> MERGE_LINE_ROAD = block(NxRoadsAndSkycrapersModBlocks.MERGE_LINE_ROAD);
	public static final RegistryObject<Item> LINE_STOP_ROAD = block(NxRoadsAndSkycrapersModBlocks.LINE_STOP_ROAD);
	public static final RegistryObject<Item> MIDDLE_LINE_DOUBLE_ROAD = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_LINE_DOUBLE_ROAD);
	public static final RegistryObject<Item> MIDDLE_TURN_LINE_ROAD = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_TURN_LINE_ROAD);
	public static final RegistryObject<Item> MIDDLE_LINE_ROAD = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_LINE_ROAD);
	public static final RegistryObject<Item> MIDDLE_CROSS_LINE_ROAD = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_CROSS_LINE_ROAD);
	public static final RegistryObject<Item> MIDDLE_T_LINE_ROAD = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_T_LINE_ROAD);
	public static final RegistryObject<Item> MIDDLE_TURN_LINE_SINGLE_ROAD = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_TURN_LINE_SINGLE_ROAD);
	public static final RegistryObject<Item> SPLIT_IN_LEFT_ROAD = block(NxRoadsAndSkycrapersModBlocks.SPLIT_IN_LEFT_ROAD);
	public static final RegistryObject<Item> SPLIT_IN_RIGHT_ROAD = block(NxRoadsAndSkycrapersModBlocks.SPLIT_IN_RIGHT_ROAD);
	public static final RegistryObject<Item> SPLIT_OUT_LEFT_ROAD = block(NxRoadsAndSkycrapersModBlocks.SPLIT_OUT_LEFT_ROAD);
	public static final RegistryObject<Item> SPLIT_OUT_RIGHT_ROAD = block(NxRoadsAndSkycrapersModBlocks.SPLIT_OUT_RIGHT_ROAD);
	public static final RegistryObject<Item> ARROW_RIGHT_ROAD = block(NxRoadsAndSkycrapersModBlocks.ARROW_RIGHT_ROAD);
	public static final RegistryObject<Item> PLAIN_SLOPE_X_1 = block(NxRoadsAndSkycrapersModBlocks.PLAIN_SLOPE_X_1);
	public static final RegistryObject<Item> DIAGONAL_EXCL_IN_E_SLOPE_ROAD_X_1 = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_IN_E_SLOPE_ROAD_X_1);
	public static final RegistryObject<Item> DIAGONAL_EXCL_IN_N_SLOPE_ROAD_X_1 = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_IN_N_SLOPE_ROAD_X_1);
	public static final RegistryObject<Item> SINGLE_MIDDLE_LINE_SLOPE_ROAD_X_1 = block(NxRoadsAndSkycrapersModBlocks.SINGLE_MIDDLE_LINE_SLOPE_ROAD_X_1);
	public static final RegistryObject<Item> DIAGONAL_EXCL_IN_SX_1 = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_IN_SX_1);
	public static final RegistryObject<Item> DIAGONAL_EXCL_IN_WX_1 = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_IN_WX_1);
	public static final RegistryObject<Item> DIAGONAL_EXCL_OUT_EX_1 = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_OUT_EX_1);
	public static final RegistryObject<Item> DIAGONAL_EXCL_OUT_NX_1 = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_OUT_NX_1);
	public static final RegistryObject<Item> DIAGONAL_EXCL_OUT_SX_1 = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_OUT_SX_1);
	public static final RegistryObject<Item> DIAGONAL_EXCL_OUT_WX_1 = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_EXCL_OUT_WX_1);
	public static final RegistryObject<Item> EXCL_LEFT_X_1 = block(NxRoadsAndSkycrapersModBlocks.EXCL_LEFT_X_1);
	public static final RegistryObject<Item> EXCL_RIGHT_X_1 = block(NxRoadsAndSkycrapersModBlocks.EXCL_RIGHT_X_1);
	public static final RegistryObject<Item> MIDDLE_DOUBLE_LINE_X_1 = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_DOUBLE_LINE_X_1);
	public static final RegistryObject<Item> SINGLE_LEFT_LINE_X_1 = block(NxRoadsAndSkycrapersModBlocks.SINGLE_LEFT_LINE_X_1);
	public static final RegistryObject<Item> SINGLE_RIGHT_LINE_X_1 = block(NxRoadsAndSkycrapersModBlocks.SINGLE_RIGHT_LINE_X_1);
	public static final RegistryObject<Item> MIDDLE_SINGLE_LINE_X_1 = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_SINGLE_LINE_X_1);
	public static final RegistryObject<Item> PLAIN_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.PLAIN_YELLOW_ROAD);
	public static final RegistryObject<Item> LEFT_ARROW_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.LEFT_ARROW_YELLOW_ROAD);
	public static final RegistryObject<Item> RIGHT_ARROW_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.RIGHT_ARROW_YELLOW_ROAD);
	public static final RegistryObject<Item> LEFT_RIGHT_ARROW_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.LEFT_RIGHT_ARROW_YELLOW_ROAD);
	public static final RegistryObject<Item> STRAIGHT_ARROW_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.STRAIGHT_ARROW_YELLOW_ROAD);
	public static final RegistryObject<Item> STRAIGHT_LEFT_ARROW_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.STRAIGHT_LEFT_ARROW_YELLOW_ROAD);
	public static final RegistryObject<Item> STRAIGHT_RIGHT_ARROW_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.STRAIGHT_RIGHT_ARROW_YELLOW_ROAD);
	public static final RegistryObject<Item> STRAIGHT_LEFT_RIGHT_ARROW_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.STRAIGHT_LEFT_RIGHT_ARROW_YELLOW_ROAD);
	public static final RegistryObject<Item> CROSSWALK_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.CROSSWALK_YELLOW_ROAD);
	public static final RegistryObject<Item> DIAGONAL_IN_EXCL_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_IN_EXCL_YELLOW_ROAD);
	public static final RegistryObject<Item> DIAGONAL_OUT_EXCL_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_OUT_EXCL_YELLOW_ROAD);
	public static final RegistryObject<Item> OUTER_LINE_EXCL_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.OUTER_LINE_EXCL_YELLOW_ROAD);
	public static final RegistryObject<Item> TURN_IN_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.TURN_IN_YELLOW_ROAD);
	public static final RegistryObject<Item> OUTER_SINGLE_LINE_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.OUTER_SINGLE_LINE_YELLOW_ROAD);
	public static final RegistryObject<Item> TURN_OUT_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.TURN_OUT_YELLOW_ROAD);
	public static final RegistryObject<Item> EXCL_ZONE_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.EXCL_ZONE_YELLOW_ROAD);
	public static final RegistryObject<Item> TURN_IN_EXCL_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.TURN_IN_EXCL_YELLOW_ROAD);
	public static final RegistryObject<Item> TURN_OUT_EXCL_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.TURN_OUT_EXCL_YELLOW_ROAD);
	public static final RegistryObject<Item> DIAGONAL_SIMPLE_LINE_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.DIAGONAL_SIMPLE_LINE_YELLOW_ROAD);
	public static final RegistryObject<Item> MERGE_LINE_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.MERGE_LINE_YELLOW_ROAD);
	public static final RegistryObject<Item> STOP_LINE_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.STOP_LINE_YELLOW_ROAD);
	public static final RegistryObject<Item> MIDDLE_DOBBLE_LINE_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_DOBBLE_LINE_YELLOW_ROAD);
	public static final RegistryObject<Item> MIDDLE_TURN_DOUBLE_LINE_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_TURN_DOUBLE_LINE_YELLOW_ROAD);
	public static final RegistryObject<Item> MIDDLE_SINGLE_LINE_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_SINGLE_LINE_YELLOW_ROAD);
	public static final RegistryObject<Item> MIDDEL_CROSS_LINE_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.MIDDEL_CROSS_LINE_YELLOW_ROAD);
	public static final RegistryObject<Item> MIDDLE_T_LINE_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_T_LINE_YELLOW_ROAD);
	public static final RegistryObject<Item> MIDDLE_TURN_LINE_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_TURN_LINE_YELLOW_ROAD);
	public static final RegistryObject<Item> SPLIT_IN_RIGHT_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.SPLIT_IN_RIGHT_YELLOW_ROAD);
	public static final RegistryObject<Item> SPLIT_IN_LEFT_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.SPLIT_IN_LEFT_YELLOW_ROAD);
	public static final RegistryObject<Item> SPLIT_OUT_RIGHT_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.SPLIT_OUT_RIGHT_YELLOW_ROAD);
	public static final RegistryObject<Item> SPLIT_OUT_LEFT_YELLOW_ROAD = block(NxRoadsAndSkycrapersModBlocks.SPLIT_OUT_LEFT_YELLOW_ROAD);
	public static final RegistryObject<Item> SINGLE_MIDDLE_LINE_YELLOW_SLOPE_X_1 = block(NxRoadsAndSkycrapersModBlocks.SINGLE_MIDDLE_LINE_YELLOW_SLOPE_X_1);
	public static final RegistryObject<Item> EXCL_LEFT_YELLOW_X_1 = block(NxRoadsAndSkycrapersModBlocks.EXCL_LEFT_YELLOW_X_1);
	public static final RegistryObject<Item> EXCL_RIGHT_YELLOW_X_1 = block(NxRoadsAndSkycrapersModBlocks.EXCL_RIGHT_YELLOW_X_1);
	public static final RegistryObject<Item> MIDDLE_DOUBLE_YELLOW_X_1 = block(NxRoadsAndSkycrapersModBlocks.MIDDLE_DOUBLE_YELLOW_X_1);
	public static final RegistryObject<Item> SINGLE_LEFT_YELLOW_X_1 = block(NxRoadsAndSkycrapersModBlocks.SINGLE_LEFT_YELLOW_X_1);
	public static final RegistryObject<Item> SINGLE_RIGHT_YELLOW_X_1 = block(NxRoadsAndSkycrapersModBlocks.SINGLE_RIGHT_YELLOW_X_1);
	public static final RegistryObject<Item> YELLOW_ROAD_DYE = REGISTRY.register("yellow_road_dye", () -> new YellowRoadDyeItem());
	public static final RegistryObject<Item> ROAD_CRAFTING_TABLE = block(NxRoadsAndSkycrapersModBlocks.ROAD_CRAFTING_TABLE);
	public static final RegistryObject<Item> SKYSCRAPER_BLOCK_1 = block(NxRoadsAndSkycrapersModBlocks.SKYSCRAPER_BLOCK_1);
	public static final RegistryObject<Item> SKYCRAPER_BLOCK_2 = block(NxRoadsAndSkycrapersModBlocks.SKYCRAPER_BLOCK_2);
	public static final RegistryObject<Item> SKYCRAPER_BLOCK_3 = block(NxRoadsAndSkycrapersModBlocks.SKYCRAPER_BLOCK_3);
	public static final RegistryObject<Item> SKYCRAPER_BLOCK_4 = block(NxRoadsAndSkycrapersModBlocks.SKYCRAPER_BLOCK_4);
	public static final RegistryObject<Item> SKYCRAPER_BLOCK_5 = block(NxRoadsAndSkycrapersModBlocks.SKYCRAPER_BLOCK_5);
	public static final RegistryObject<Item> SKYCRAPER_BLOCK_6 = block(NxRoadsAndSkycrapersModBlocks.SKYCRAPER_BLOCK_6);
	public static final RegistryObject<Item> CONCRETE_1 = block(NxRoadsAndSkycrapersModBlocks.CONCRETE_1);
	public static final RegistryObject<Item> CONCRETE_2 = block(NxRoadsAndSkycrapersModBlocks.CONCRETE_2);
	public static final RegistryObject<Item> GRANITE_1 = block(NxRoadsAndSkycrapersModBlocks.GRANITE_1);
	public static final RegistryObject<Item> GRANITE_2 = block(NxRoadsAndSkycrapersModBlocks.GRANITE_2);
	public static final RegistryObject<Item> GRANITE_3 = block(NxRoadsAndSkycrapersModBlocks.GRANITE_3);
	public static final RegistryObject<Item> MARBLE_1 = block(NxRoadsAndSkycrapersModBlocks.MARBLE_1);
	public static final RegistryObject<Item> MARBLE_2 = block(NxRoadsAndSkycrapersModBlocks.MARBLE_2);
	public static final RegistryObject<Item> MARBLE_3 = block(NxRoadsAndSkycrapersModBlocks.MARBLE_3);
	public static final RegistryObject<Item> MARBLE_4 = block(NxRoadsAndSkycrapersModBlocks.MARBLE_4);
	public static final RegistryObject<Item> MARBLE_5 = block(NxRoadsAndSkycrapersModBlocks.MARBLE_5);
	public static final RegistryObject<Item> MARBLE_6 = block(NxRoadsAndSkycrapersModBlocks.MARBLE_6);
	public static final RegistryObject<Item> MARBLE_7 = block(NxRoadsAndSkycrapersModBlocks.MARBLE_7);
	public static final RegistryObject<Item> MARBLE_8 = block(NxRoadsAndSkycrapersModBlocks.MARBLE_8);
	public static final RegistryObject<Item> PAVEMENT_CRACKED_1 = block(NxRoadsAndSkycrapersModBlocks.PAVEMENT_CRACKED_1);
	public static final RegistryObject<Item> PAVEMENT_CRACKED_2 = block(NxRoadsAndSkycrapersModBlocks.PAVEMENT_CRACKED_2);
	public static final RegistryObject<Item> PAVEMENT_CRACKED_3 = block(NxRoadsAndSkycrapersModBlocks.PAVEMENT_CRACKED_3);
	public static final RegistryObject<Item> SIDEWALK_1 = block(NxRoadsAndSkycrapersModBlocks.SIDEWALK_1);
	public static final RegistryObject<Item> SIDEWALK_2 = block(NxRoadsAndSkycrapersModBlocks.SIDEWALK_2);
	public static final RegistryObject<Item> SIDEWALK_3 = block(NxRoadsAndSkycrapersModBlocks.SIDEWALK_3);
	public static final RegistryObject<Item> SIDEWALK_4 = block(NxRoadsAndSkycrapersModBlocks.SIDEWALK_4);
	public static final RegistryObject<Item> SIDEWALK_5 = block(NxRoadsAndSkycrapersModBlocks.SIDEWALK_5);
	public static final RegistryObject<Item> SIDEWALK_6 = block(NxRoadsAndSkycrapersModBlocks.SIDEWALK_6);
	public static final RegistryObject<Item> SIDEWALK_7 = block(NxRoadsAndSkycrapersModBlocks.SIDEWALK_7);
	public static final RegistryObject<Item> SIDEWALK_8 = block(NxRoadsAndSkycrapersModBlocks.SIDEWALK_8);
	public static final RegistryObject<Item> STONE_1 = block(NxRoadsAndSkycrapersModBlocks.STONE_1);
	public static final RegistryObject<Item> STONE_2 = block(NxRoadsAndSkycrapersModBlocks.STONE_2);
	public static final RegistryObject<Item> STONE_3 = block(NxRoadsAndSkycrapersModBlocks.STONE_3);
	public static final RegistryObject<Item> STONE_4 = block(NxRoadsAndSkycrapersModBlocks.STONE_4);
	public static final RegistryObject<Item> STONE_5 = block(NxRoadsAndSkycrapersModBlocks.STONE_5);
	public static final RegistryObject<Item> STONE_6 = block(NxRoadsAndSkycrapersModBlocks.STONE_6);
	public static final RegistryObject<Item> STONE_7 = block(NxRoadsAndSkycrapersModBlocks.STONE_7);
	public static final RegistryObject<Item> STONE_BRICK_CRACKED_1 = block(NxRoadsAndSkycrapersModBlocks.STONE_BRICK_CRACKED_1);
	public static final RegistryObject<Item> STONE_BRICK_CRACKED_2 = block(NxRoadsAndSkycrapersModBlocks.STONE_BRICK_CRACKED_2);
	public static final RegistryObject<Item> STONE_BRICK_CRACKED_3 = block(NxRoadsAndSkycrapersModBlocks.STONE_BRICK_CRACKED_3);
	public static final RegistryObject<Item> STONE_BRICK_CRACKED_4 = block(NxRoadsAndSkycrapersModBlocks.STONE_BRICK_CRACKED_4);
	public static final RegistryObject<Item> STONE_BRICK_CRACKED_5 = block(NxRoadsAndSkycrapersModBlocks.STONE_BRICK_CRACKED_5);
	public static final RegistryObject<Item> STONE_BRICK_CRACKED_6 = block(NxRoadsAndSkycrapersModBlocks.STONE_BRICK_CRACKED_6);
	public static final RegistryObject<Item> WOOD_CEILING_1 = block(NxRoadsAndSkycrapersModBlocks.WOOD_CEILING_1);
	public static final RegistryObject<Item> WOOD_CEILING_2 = block(NxRoadsAndSkycrapersModBlocks.WOOD_CEILING_2);
	public static final RegistryObject<Item> WOOD_CEILING_3 = block(NxRoadsAndSkycrapersModBlocks.WOOD_CEILING_3);
	public static final RegistryObject<Item> WOOD_CEILING_4 = block(NxRoadsAndSkycrapersModBlocks.WOOD_CEILING_4);
	public static final RegistryObject<Item> WOOD_FLOOR_LONG_1 = block(NxRoadsAndSkycrapersModBlocks.WOOD_FLOOR_LONG_1);
	public static final RegistryObject<Item> WOOD_FLOOR_LONG_2 = block(NxRoadsAndSkycrapersModBlocks.WOOD_FLOOR_LONG_2);
	public static final RegistryObject<Item> WOOD_FLOOR_LONG_3 = block(NxRoadsAndSkycrapersModBlocks.WOOD_FLOOR_LONG_3);
	public static final RegistryObject<Item> WOOD_FLOOR_LONG_4 = block(NxRoadsAndSkycrapersModBlocks.WOOD_FLOOR_LONG_4);
	public static final RegistryObject<Item> WOOD_FLOOR_LONG_5 = block(NxRoadsAndSkycrapersModBlocks.WOOD_FLOOR_LONG_5);
	public static final RegistryObject<Item> WOOD_FLOOR_LONG_6 = block(NxRoadsAndSkycrapersModBlocks.WOOD_FLOOR_LONG_6);
	public static final RegistryObject<Item> CLASS_0 = block(NxRoadsAndSkycrapersModBlocks.CLASS_0);
	public static final RegistryObject<Item> GLASS_1 = block(NxRoadsAndSkycrapersModBlocks.GLASS_1);
	public static final RegistryObject<Item> GLASS_2 = block(NxRoadsAndSkycrapersModBlocks.GLASS_2);
	public static final RegistryObject<Item> GLASS_3 = block(NxRoadsAndSkycrapersModBlocks.GLASS_3);
	public static final RegistryObject<Item> GLASS_4 = block(NxRoadsAndSkycrapersModBlocks.GLASS_4);
	public static final RegistryObject<Item> GLASS_5 = block(NxRoadsAndSkycrapersModBlocks.GLASS_5);
	public static final RegistryObject<Item> GLASS_6 = block(NxRoadsAndSkycrapersModBlocks.GLASS_6);
	public static final RegistryObject<Item> GLASS_7 = block(NxRoadsAndSkycrapersModBlocks.GLASS_7);
	public static final RegistryObject<Item> GLASS_8 = block(NxRoadsAndSkycrapersModBlocks.GLASS_8);
	public static final RegistryObject<Item> GLASS_9 = block(NxRoadsAndSkycrapersModBlocks.GLASS_9);
	public static final RegistryObject<Item> GLASS_10 = block(NxRoadsAndSkycrapersModBlocks.GLASS_10);
	public static final RegistryObject<Item> GLASS_GREY_0 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_0);
	public static final RegistryObject<Item> GLASS_GREY_1 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_1);
	public static final RegistryObject<Item> GLASS_GREY_2 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_2);
	public static final RegistryObject<Item> GLASS_GREY_3 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_3);
	public static final RegistryObject<Item> GLASS_GREY_4 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_4);
	public static final RegistryObject<Item> GLASS_GREY_5 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_5);
	public static final RegistryObject<Item> GLASS_GREY_6 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_6);
	public static final RegistryObject<Item> GLASS_GREY_7 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_7);
	public static final RegistryObject<Item> GLASS_GREY_8 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_8);
	public static final RegistryObject<Item> GLASS_GREY_9 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_9);
	public static final RegistryObject<Item> GLASS_GREY_10 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREY_10);
	public static final RegistryObject<Item> GLASS_GREEN_0 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_0);
	public static final RegistryObject<Item> GLASS_GREEN_1 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_1);
	public static final RegistryObject<Item> GLASS_GREEN_2 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_2);
	public static final RegistryObject<Item> GLASS_GREEN_3 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_3);
	public static final RegistryObject<Item> GLASS_GREEN_4 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_4);
	public static final RegistryObject<Item> GLASS_GREEN_5 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_5);
	public static final RegistryObject<Item> GLASS_GREEN_6 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_6);
	public static final RegistryObject<Item> GLASS_GREEN_7 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_7);
	public static final RegistryObject<Item> GLASS_GREEN_8 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_8);
	public static final RegistryObject<Item> GLASS_GREEN_9 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_9);
	public static final RegistryObject<Item> GLASS_GREEN_10 = block(NxRoadsAndSkycrapersModBlocks.GLASS_GREEN_10);
	public static final RegistryObject<Item> OUTER_LINE_EX_ROAD_ROTATED = block(NxRoadsAndSkycrapersModBlocks.OUTER_LINE_EX_ROAD_ROTATED);

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
